DEFRA/ffc-pay-submission

Jenkinsfile, app/index.js, docker-compose.test.yaml, package-lock.json, package.json
https://eaflood.atlassian.net/browse/SFI-1603
=> Add timestamp to logs

app/config/db-config.js, package.json
Fix implemented as in https://github.com/Azure/azure-sdk-for-js/issues/13436
Also consistent with `ffc-pay-processing`
https://eaflood.atlassian.net/browse/SFI-1699
=> Extend identity acquire time

README.md, app/data/models/payment-request.js, app/inbound/get-existing-payment-request.js, app/inbound/index.js, changelog/db.changelog-1.6.xml, changelog/db.changelog.xml, docs/asyncapi.yaml, package-lock.json, package.json, test/integration/local/inbound/save-payment-request.test.js
https://eaflood.atlassian.net/browse/SFI-1816﻿
=> Update duplicate check

changelog/db.changelog-1.8.xml, changelog/db.changelog.xml, package.json
https://eaflood.atlassian.net/browse/SFI-1824﻿
=> Add additional schemes

changelog/db.changelog-1.11.xml, changelog/db.changelog.xml, package.json
https://eaflood.atlassian.net/browse/SFI-2264
=> Update SFI batch properties

app/batching/get-content.js, app/batching/get-ledger-line.js, app/batching/get-vendor-line.js, app/schemes.js, package-lock.json, package.json, test/integration/local/batching/generate-batches.test.js, test/integration/local/batching/get-content.test.js
https://eaflood.atlassian.net/browse/SFI-2335
=> Remove agreement number from "Siti" schemes

README.md, package.json
https://dev.azure.com/defragovuk/DEFRA-FFC/_sprints/taskboard/DEFRA-FFC%20Payments%20Team/DEFRA-FFC/Payment%20Service/Pay%20Sprint%2042
=> 121303-update-readme

app/batching/get-ledger-line.js, app/batching/get-vendor-line.js, app/config/index.js, app/constants/schemes.js, app/data/models/invoice-line.js, app/index.js, app/messaging/create-message.js, app/messaging/index.js, app/messaging/process-payment-message.js, app/messaging/send-file-transfer-message.js, changelog/db.changelog-1.13.xml, changelog/db.changelog.xml, package.json, test/integration/local/batching/get-content.test.js, test/unit/batching/get-ledger-line.test.js, test/unit/batching/get-vendor-line.test.js
https://dev.azure.com/defragovuk/DEFRA-FFC/_workitems/edit/158551
https://dev.azure.com/defragovuk/DEFRA-FFC/_workitems/edit/158550﻿
=> Support BPS and CS

app/batching/get-vendor-line.js, app/batching/vendor-lines/set-payment-type.js, app/data/models/payment-request.js, changelog/db.changelog-1.16.xml, changelog/db.changelog.xml, docs/asyncapi.yaml, package.json, test/unit/batching/vendor-lines/set-payment-type.test.js
https://dev.azure.com/defragovuk/DEFRA-FFC/_sprints/taskboard/DEFRA-FFC%20Payments%20Team/DEFRA-FFC/Payment%20Service/Sprint%2002?workitem=166913
=>  166913-include-advance-payment-status-in-cs

app/batching/vendor-lines/get-legacy-identifier.js, app/batching/vendor-lines/get-vendor-line.js, package-lock.json, package.json, test/unit/batching/vendor-lines/get-legacy-identifier.test.js, test/unit/batching/vendor-lines/get-vendor-line.test.js
https://eaflood.atlassian.net/browse/DOC-709
=> Add currency and legacy identifier to AR output

app/config/db-config.js, helm/ffc-pay-submission/values.yaml, package.json
- **Improve concurrency**
- **bump version**
=> Improve concurrency

app/batching/ledger-lines/get-ledger-line.js, package.json, test/unit/batching/ledger-lines/get-ledger-line.test.js
https://eaflood.atlassian.net/browse/DOC-848
=>  use payment request agreement number for CS rather than invoice line

README.md, docker-compose.debug.yaml, docker-compose.link.yaml, docker-compose.migrate.yaml, docker-compose.override.yaml, docker-compose.test.debug.yaml, docker-compose.test.watch.yaml, docker-compose.test.yaml, docker-compose.yaml, package.json, scripts/start, scripts/test
- Removed version
- Moved from docker-compose to docker compose
=> DOC-1422 : moved command docker-compose to docker compose and removed version

app/constants/manual-sources.js, app/constants/pillars.js, package.json
https://eaflood.atlassian.net/browse/DOC-1462
=> add DP options for manual payments

app/config/index.js, package.json
https://eaflood.atlassian.net/browse/DOC-1644
=> increase submission interval

app/constants/manual-sources.js, package-lock.json, package.json, test/unit/batching/vendor-lines/get-source.test.js
https://eaflood.atlassian.net/browse/DOC-1500
=> change source code for manual sfip payments

app/constants/manual-sources.js, app/constants/pillars.js, package.json
https://eaflood.atlassian.net/browse/DOC-1462
=> add early esfio manual capability

app/config/index.js, package.json
Part of on-going issues with IMPS return files.
=> increase batch interval

app/batching/vendor-lines/get-batch-number.js, app/batching/vendor-lines/get-vendor-line.js, package-lock.json, package.json, test/unit/batching/vendor-lines/get-batch-number.test.js
https://eaflood.atlassian.net/browse/DOC-1738
=> set vendor sequence as batch sequence rather than journal sequence, IMPS & FC

app/batching/ledger-lines/get-description.js, package-lock.json, package.json, test/unit/batching/ledger-lines/get-description.test.js
https://eaflood.atlassian.net/browse/DOC-1926
=> swap eur symbol for eur abbreviation

app/constants/manual-sources.js, helm/ffc-pay-submission/templates/config-map.yaml, package-lock.json, package.json
https://eaflood.atlassian.net/browse/DOC-2308
=> change CS manual pillar output

app/config/index.js, app/event/send-submission-batch-event.js, app/event/send-submission-transfer-event.js, app/messaging/send-file-transfer-message.js, helm/ffc-pay-submission/templates/config-map.yaml, helm/ffc-pay-submission/values.yaml, package-lock.json, package.json, test/unit/event/send-submission-batch-event.test.js, test/unit/event/send-submission-transfer-event.test.js
https://eaflood.atlassian.net/browse/DOC-2357
=> remove use v2 events
